version: "3"
services:
  api:
    build:
      context: .
    volumes:
      - ./:/usr/src
      - bundle:/usr/local/bundle
    command: sh -c "rm -f tmp/pids/server.pid && bundle install && rails server -b 0.0.0.0"
    ports:
      - 3036:3000
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - 33333:3306
    volumes:
      - ./tmp/data:/var/lib/mysql

volumes:
  bundle: {}
