version: "3"
services:
  api:
    build:
      context: .
    volumes:
      - ./:/usr/src
      - bundle:/usr/local/bundle
    command: sh -c "rm -f tmp/pids/server.pid && bundle install && rails server -b 0.0.0.0"
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: src_development
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  bundle: {}
  db-data:
    driver: local